# permissions for end users to view performanceprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performanceprofile-viewer-role
rules:
- apiGroups:
  - performance.openshift.io
  resources:
  - performanceprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - performance.openshift.io
  resources:
  - performanceprofiles/status
  verbs:
  - get
